Document: ethercalc
Title: Debian ethercalc Manual
Author: <insert document author here>
Abstract: This manual describes what ethercalc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ethercalc/ethercalc.sgml.gz

Format: postscript
Files: /usr/share/doc/ethercalc/ethercalc.ps.gz

Format: text
Files: /usr/share/doc/ethercalc/ethercalc.text.gz

Format: HTML
Index: /usr/share/doc/ethercalc/html/index.html
Files: /usr/share/doc/ethercalc/html/*.html
